import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/nav-bar/Navbar";
import Footer from "@/components/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Car parking system",
  description: "Generated by Ahmed Yasser",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container">
          <Navbar />
          <div className="containerChild">{children}</div>

          <Footer />
        </div>
      </body>
    </html>
  );
}
